site_name: repath
site_description: Vector Graphics Manipulation Tool
site_author: Konstantinos Kaloutas
site_url: https://repath.studio/
copyright: 2022 © Konstantinos Kaloutas

repo_url: https://github.com/sprocketc/repath-studio
repo_name: sprocketc/repath-studio

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  custom_dir: theme
  favicon: assets/images/favicon.png
  features:
  - navigation.tabs
  - navigation.expand
  - navigation.indexes
  - announce.dismiss
  - navigation.top
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/images/logo.svg
  palette:
    scheme: slate
    primary: pink-700
    accent: pink
  font: false
  
nav:
  - Home: index.md
  - Get Studio: 
    - get-studio/download.md
    - get-studio/build-from-source.md
  - Docs: 
    - docs/keyboard-shortcuts.md
  - Contribute: 
    - contribute/develop.md
    - CLA: contribute/cla.md
  - Roadmap: 
    - roadmap/roadmap.md
    - roadmap/changelog.md
  - Blog: 
    - blog/posts.md
    - blog/tags.md
    
extra:
  generator: false
  social:
  - icon: fontawesome/solid/at
    link: mailto:contact@repath.studio
  - icon: fontawesome/brands/discord
    link: https://discord.gg/yzjY6W6ame
  - icon: fontawesome/brands/twitter
    link: https://www.twitter.com/repath_studio/
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/repath.studio/
  - icon: fontawesome/brands/github
    link: https://github.com/sprocketc/
  consent:
    title: Cookie consent
    description: >- # 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our website better.
  analytics: 
    provider: google
    property: G-EJXPVG0694
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences 
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - tags
  - social:
      cards_color:
          fill: "#1c1d26" 
          text: "#FFFFFF"
  - blogging:
      dirs:
        - blog/articles
      template: theme/overrides/custom-blog.html
      features:
        tags:
          index_page: blog/tags.md

