site_name: repath
site_description: Scalable Vector Graphics Manipulation
site_author: Konstantinos Kaloutas
site_url: https://repath.studio/
copyright: 2022 © Konstantinos Kaloutas

repo_url: https://github.com/re-path/studio
repo_name: re-path/studio

extra_css:
  - assets/stylesheets/extra.css
  
extra_javascript:
  - assets/javascripts/snap.svg-min.js

theme:
  name: material
  custom_dir: theme
  favicon: assets/images/favicon.png
  features:
  - navigation.tabs
  - navigation.expand
  - navigation.indexes
  - announce.dismiss
  - navigation.top
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/images/logo.svg
  palette:
    scheme: slate
    primary: pink-700
    accent: pink
  font: false
  
nav:
  - Home: index.md
  - Get Studio:
    - get-studio/download.md
    - get-studio/build-from-source.md
  - Docs:
    - docs/getting-started.md
    - docs/shortcuts.md
  - Contribute:
    - contribute/develop.md
    - CLA: contribute/cla.md
    - contribute/support-us.md  
  - Roadmap:
    - roadmap/roadmap.md
    - roadmap/changelog.md

extra:
  generator: false
  social:
  - icon: fontawesome/solid/at
    link: mailto:contact@repath.studio
    name: Email us
  - icon: custom/matrix 
    link: https://matrix.to/#/#repath.studio:matrix.org
  - icon: fontawesome/brands/discord
    link: https://discord.gg/yzjY6W6ame
  - icon: fontawesome/brands/twitter
    link: https://www.twitter.com/repath_studio/
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/repath.studio/
  - icon: fontawesome/brands/github
    link: https://github.com/re-path/
  consent:
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    title: Cookie consent
    description: >- # 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our website better.
  analytics: 
    provider: google
    property: G-EJXPVG0694
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences 
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - tags
  - search
